const $ = (id) => document.getElementById(id);
let socket, token = '', currentId = null, timer;
const api = async (path, options = {}) => { const response = await fetch(path, { ...options, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...(options.headers || {}) } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); };
const render = async () => { const { notes } = await api('/api/notes'); $('notesList').replaceChildren(...notes.map((note) => { const button = document.createElement('button'); button.textContent = `${note.title} ${note.preview}`; button.addEventListener('click', () => open(note.id)); const li = document.createElement('li'); li.append(button); return li; })); $('emptyNotes').classList.toggle('hidden', notes.length > 0); };
const open = async (id) => { const { note } = await api(`/api/notes/${id}`); currentId = note.id; $('noteTitle').value = note.title; $('noteBody').value = note.body; };
const saveSoon = () => { clearTimeout(timer); $('saveStatus').textContent = ''; timer = setTimeout(async () => { const { note } = await api('/api/notes', { method: 'POST', body: JSON.stringify({ id: currentId, title: $('noteTitle').value || 'Untitled', body: $('noteBody').value }) }); currentId = note.id; $('saveStatus').textContent = 'Saved'; await render(); }, 250); };
const showNotes = async () => { $('viewerPanel').classList.add('hidden'); $('notesPanel').classList.remove('hidden'); $('viewerTab').setAttribute('aria-selected', 'false'); $('notesTab').setAttribute('aria-selected', 'true'); await render(); };
const connect = () => { socket = new WebSocket(`${location.origin.replace('http', 'ws')}/ws`); socket.onopen = () => socket.send(JSON.stringify({ type: 'auth', code: $('accessCode').value })); socket.onmessage = async (event) => { const message = JSON.parse(event.data); if (message.type === 'auth') { if (!message.ok) return $('authError').classList.remove('hidden'); token = message.token; $('authCard').classList.add('hidden'); $('app').classList.remove('hidden'); } if (message.type === 'notes_changed' && token) await render(); }; socket.onclose = () => $('reconnectBanner').classList.remove('hidden'); };
$('connectButton').addEventListener('click', connect); $('notesTab').addEventListener('click', showNotes); $('viewerTab').addEventListener('click', () => { $('viewerPanel').classList.remove('hidden'); $('notesPanel').classList.add('hidden'); }); $('newNote').addEventListener('click', () => { currentId = null; $('noteTitle').value = ''; $('noteBody').value = ''; }); $('noteTitle').addEventListener('input', saveSoon); $('noteBody').addEventListener('input', saveSoon); $('deleteNote').addEventListener('click', async () => { if (!currentId) return; await api(`/api/notes/${currentId}`, { method: 'DELETE' }); currentId = null; $('noteTitle').value = ''; $('noteBody').value = ''; await render(); });
